language: go
go:
  - 1.8

install:
  - go get -v ./...
  - go get github.com/onsi/ginkgo
  - go get gopkg.in/yaml.v2
  - go install github.com/onsi/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race